#!/bin/zsh

# Set my theme. Muse is one I like because they have icons, git support, and 
# muse seems to work without additional configuration / support.
export ZSH_THEME="muse"
# I like to use the vim editor
export EDITOR=vim
# Tell zsh to auto-select the first completion when there is only one
zstyle '*' single-ignored complete
# Load these plugins when zsh starts (it will start AFTER this config  is processed
plugins=(brew dircycle gem git osx)
# Tell zsh to show red dots while searching for a completion
COMPLETION_WAITING_DOTS="true"

#
# OSX Settings
#
if expr "$OSTYPE" : darwin >/dev/null ; then
	# Open the TotalTerminal app
	open -a TotalTerminal 2>/dev/null
fi

# Run RVM init
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # This loads RVM into a shell session.

# vim: set ft=zsh :
