#!/bin/zsh

# Set my theme. Muse is one I like because they have icons, git support, and
# muse seems to work without additional configuration / support.
export ZSH_THEME="muse"
# I like to use the vim editor
export EDITOR='emacs'
# Tell zsh to auto-select the first completion when there is only one
zstyle '*' single-ignored complete
# Load these plugins when zsh starts (it will start AFTER this config  is processed
plugins=(brew dircycle gem git)
# Tell zsh to show red dots while searching for a completion
COMPLETION_WAITING_DOTS="true"
# Disable autocorrect
unsetopt correct_all
export DISABLE_CORRECTION="true"
# Enable more brace expansion
setopt braceccl

#
# OSX Settings
#
if expr "$OSTYPE" : darwin >/dev/null ; then
	# Open the TotalTerminal app
	# open -a TotalTerminal 2>/dev/null
	# Setup homebrew
	export PATH=/usr/local/bin:$PATH
	# Homebrew uses a GitHub API token
	export HOMEBREW_GITHUB_API_TOKEN=$(cat ~/.ssh/GITHUB_API_TOKEN)

	# Setup a trash function
	trash() {
		CYAN="\x1B[36m"
		RED="\x1B[31m"
		RESET="\x1B[0m"

		for file in $@ ; do
			# Normalize the path
			file=$(cd $(dirname $file); pwd)/$(basename $file)
			# If the file is found, then delete. Otherwise error
			if [[ -e "$file" ]] ; then
				echo -e "Removing file ${CYAN}${file}${RESET}"
				/usr/bin/env osascript -e "tell application \"Finder\" to delete POSIX file \"${file}\"" 1>/dev/null
			else
				echo -e "${RED}Cannot find the file ${CYAN}${file}${RESET}"
			fi
		done
	}
fi

# Run RVM init
if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
	. "$HOME/.rvm/scripts/rvm" # This loads RVM into a shell session.
	PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
fi

# Add my personal bin set
PATH=/usr/local/sbin:$PATH:~/usr/bin
# Configure Byobu
export BYOBU_PREFIX=$(brew --prefix)

# vim: set ft=zsh :
